sonar.projectKey=Islewright_Islewright
sonar.organization=islewright

sonar.projectName=Islewright
sonar.projectVersion=0.1.0

sonar.sources=client,common,server
sonar.coverage.exclusions=client/**,server/**,**/tests/**
sonar.coverageReportPaths=coverage.xml
sonar.sourceEncoding=UTF-8

sonar.cfamily.compile-commands=build/compile_commands.json
